### ISSUE TITLE
How use for charmm36m for protein, glycans and lipids. 

### ISSUE THREAD

**Issue by georopon** [ErikMarklund/mkvsites#2]
How can make to set lipids, protein, and glycans,? 
Also what're modification into MDP files, for example using contrainst = all-bond o h-bonds ???? or other setups

**Comment by ErikMarklund** [comment]
Sorry for being slow with this. Project has been a bit dormant for a while.

See the tutorials included with the source code. In short 1) run topinspect.py to identify new atomtypes and interaction types that need to be added to the force field files, and optionally to make an rtp file. 2) run mkvsites.py to derive angle constraints and vsite parameters that need to go into the force field files.

Vsites are normally only used with constraints = all-bonds. Only constraining h-bonds doesn't allow as long time steps, defeating the point of vsites.

**Comment by ErikMarklund** [comment]
One more thing: For 5 fs and maybe even 4 fs time steps, use lincs-order = 6 or higher. The gromacs manual even says so, but it is easily missed.

**Comment by ErikMarklund** [comment]
Lastly, there have been a few updates to the code since you posted the issue. If you were having problems, maybe some bugs have been fixed since.
